f#!/bin/bash
# Pass path of the directory of the output directory generated by KRPano(which cuts the stitched pano) as first argument
# The result will be stored in the the input directory given
cd $1
name=""
blur_folder="blur_"
NAME=""

for folder in `ls`
do
    NAME=`echo "$folder" | cut -d'.' -f1`
    name="blur_$NAME"
    mkdir "$name"
    mv $folder $NAME
    cd $NAME
    for file in `ls`
    do
        if [ $file == "mobile_b.jpg" ] || [ $file == "mobile_d.jpg" ] || [ $file == "mobile_f.jpg" ] || [ $file == "mobile_l.jpg" ] || [ $file == "mobile_r.jpg" ] || [ $file == "mobile_u.jpg" ]
        then
            command="convert $file -resize 256x256 ../blur_$NAME/$file"
            $command
        else
            rm -rf $file
        fi
    done
    cd ..
done
